
---
- name: Install PHP and Apache for PSM
  hosts: php_servers
  vars:
    install_dir: /usr/local/greatfire
    psm_repo_url: https://github.com/stevenmcdonald/psm/
  become: no
  remote_user: root

  tasks:
    - name: Install requirements
      ansible.builtin.apt:
        pkg:
          - apache2
          - libapache2-mod-php
          - php
          - php-curl
          - php-mongodb
          - sudo
          - vim-nox

    # configure Apache
    - name: Disable prefork module
      ansible.builtin.file:
        path: /etc/apache2/mods-enabled/mpm_prefork.conf
        state: absent

    - name: Update apache2 worker conf
      ansible.builtin.copy:
        src: mpm_worker.conf
        dest: /etc/apache2/mods-available/mpm_worker.conf

    - name: Enable the worker module
      ansible.builtin.file:
        src: /etc/apache2/mods-available/mpm_worker.conf
        path: /etc/apache2/mods-enabled/mpm_worker.conf
        state: link

    - name: Disable the default site
      ansible.builtin.file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent

    - name: Install the PSM Apache config
      ansible.builtin.copy:
        src: psm_apache.conf
        dest: /etc/apache2/sites-available/psm.conf

    - name: Enable the PSM Apache config
      ansible.builtin.file:
        src: /etc/apache2/sites-available/psm.conf
        dest: /etc/apache2/sites-enabled/psm.conf
        state: link

    # configure user, directory
    - name: Create psm user
      ansible.builtin.user:
        name: psm

    - name: Create install directory
      ansible.builtin.file:
        path: "{{ install_dir }}"
        state: directory

    - name: Pull the code
      ansible.builtin.git:
        repo: "{{ psm_repo_url }}"
        desg: "{{ install_dir }}"
        version: main
        force: yes
      become: yes
      become_user: psm

    - name: Reload Apache
      ansible.builtin.systemd:
        name: apache2
        state: reloaded
